image: node:14

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - web
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  only:
    - web
  script:
    - ls -la
    - mv dist public
  artifacts:
    paths:
      - public
  dependencies:
    - build
