export default {
  UNKNOWN: 'UNKNOWN',

  // Categories
  ADD_CATEGORY: 'ADD_CATEGORY',
  EDIT_CATEGORY: 'EDIT_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',

  // Tags
  ADD_TAG: 'ADD_TAG',
  EDIT_TAG: 'EDIT_TAG',
  DELETE_TAG: 'DELETE_TAG',

  // Posts
  DELETE_POST: 'DELETE_POST',
  PUBLISH_POST: 'PUBLISH_POST',
  UNPUBLISH_POST: 'UNPUBLISH_POST',
};
